name: Build APK (minimal)

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android APK
        run: |
          chmod +x android/gradlew
          cd android
          
          # Create upload keystore for consistent signing
          keytool -genkeypair -v -keystore upload.keystore -alias upload -keyalg RSA -keysize 2048 -validity 10000 -storepass uploadpass -keypass uploadpass -dname "CN=Upload,O=Android,C=US" -noprompt
          
          # Configure Gradle to use the upload keystore for release builds
          echo "android.useAndroidX=true" > gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "org.gradle.daemon=true" >> gradle.properties
          
          ./gradlew clean assembleRelease --no-daemon --refresh-dependencies

      - name: Get version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: svampkartan-v${{ steps.version.outputs.version }}-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
