      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Generate Android launcher icons from SVG
        run: |
          convert public/icon-192.svg -resize 48x48 android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 72x72 android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 96x96 android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
          # För adaptive icons (v26+)
          convert public/icon-192.svg -resize 192x192 android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_foreground.png
# This GitHub Actions workflow builds your Android APK in the cloud and uploads it as an artifact.
# Place this file in .github/workflows/build-apk.yml in your repo.

name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Generate Android launcher icons from SVG
        run: |
          convert public/icon-192.svg -resize 48x48 android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 72x72 android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 96x96 android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
          convert public/icon-192.svg -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
          # För adaptive icons (v26+)
          convert public/icon-192.svg -resize 192x192 android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_foreground.png

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static site for Android
        run: |
          # Ta bort basePath och assetPrefix temporärt för Android WebView
          cp next.config.js next.config.js.bak
          sed '/basePath/d;/assetPrefix/d' next.config.js.bak > next.config.js
          npm run build
          mv next.config.js.bak next.config.js

      - name: Install Capacitor Android
        run: npm install @capacitor/android

      - name: Install Capacitor CLI globally
        run: npm install -g @capacitor/cli

      - name: Copy web build to Android assets
        run: |
          rm -rf android/app/src/main/assets/public
          mkdir -p android/app/src/main/assets/public
          cp -r out/* android/app/src/main/assets/public/
      - name: Ensure Capacitor Android platform exists
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK with Gradle
        run: |
          export JAVA_HOME="/usr/lib/jvm/temurin-21-jdk-amd64"
          export PATH="$JAVA_HOME/bin:$PATH"
          export JAVA_TOOL_OPTIONS="-Dorg.gradle.java.home=/usr/lib/jvm/temurin-21-jdk-amd64"
          java -version
          cd android
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --refresh-dependencies

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
